networks:
  secure_net:
    driver: bridge

services:

  postgres:
    image: postgres:18
    container_name: postgres
    networks: [secure_net]
    volumes:
      - ./data/postgres:/var/lib/postgresql
    environment:
      POSTGRES_DB: sentinels_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: superadmin
    ports:
      - "5432:5432"

  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    container_name: keycloak
    command: start-dev
    networks: [secure_net]
    volumes:
      - ./data/keycloak:/opt/keycloak/data
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  vault:
    image: hashicorp/vault:1.15
    container_name: vault
    networks: [secure_net]
    volumes:
      - ./data/vault:/vault/file
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: dev-root-token
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    command: vault server -dev -dev-root-token-id=dev-root-token

  django:
    build: .
    container_name: django
    networks: [secure_net]
    volumes:
      - ./src/backend:/app
      - ./data/django:/app/media
    depends_on:
      - postgres
      - keycloak
      - vault
    ports:
      - "8000:8000"
 