networks:
  secure_net:
    driver: bridge

services:

  postgres:
    image: postgres:16
    container_name: postgres
    networks: [secure_net]
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: myapp
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: superadmin
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: redis
    networks: [secure_net]
    volumes:
      - ./data/redis:/data
    ports:
      - "6379:6379"

  keycloak:
    image: quay.io/keycloak/keycloak:25.0
    container_name: keycloak
    command: start-dev
    networks: [secure_net]
    volumes:
      - ./data/keycloak:/opt/keycloak/data
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: superadmin
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  vault:
    image: hashicorp/vault:1.15
    container_name: vault
    networks: [secure_net]
    volumes:
      - ./data/vault:/vault/file
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: dev-root-token
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    command: vault server -dev -dev-root-token-id=dev-root-token

  django:
    build: .
    container_name: django
    networks: [secure_net]
    volumes:
      - ./src/backend:/app
      - ./data/django/media:/app/media
    depends_on:
      - postgres
      - keycloak
      - vault
      - redis
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000

  celery:
    build: .
    container_name: celery
    networks: [secure_net]
    command: celery -A core worker -l info
    volumes:
      - ./src/backend:/app
    depends_on:
      - django
      - redis
